CREATE TABLE IF NOT EXISTS TIME (
   ID BIGINT AUTO_INCREMENT NOT NULL,
   VERSION BIGINT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS JOGADOR (
   ID BIGINT AUTO_INCREMENT NOT NULL,
   VERSION BIGINT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   APELIDO VARCHAR(50) NULL,
   DT_NASCIMENTO DATE NULL,
   RG VARCHAR(10) NULL,
   DDD_TELEFONE VARCHAR(2) NULL,
   TELEFONE  VARCHAR(10) NULL,
   DDD_CELULAR VARCHAR(2) NOT NULL,
   CELULAR  VARCHAR(10) NOT NULL,
   EMAIL VARCHAR(50) NULL,
   FACEBOOK VARCHAR(50) NULL,
   FOTO BLOB NULL,
   DT_INCLUSAO DATE NOT NULL,
   PRIMARY KEY (ID)   
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS POSICAO(
   ID BIGINT AUTO_INCREMENT NOT NULL,
   NOME VARCHAR(50) NOT NULL,
   MODALIDADE VARCHAR(20) NOT NULL, /*FUTSAL, AREIA, CAMPO, SUÍÇO*/
   PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS JOGADOR_POSICAO(
   ID BIGINT AUTO_INCREMENT NOT NULL,
   JOGADOR_ID BIGINT NOT NULL,
   POSICAO_ID BIGINT NOT NULL,
   PRIMARY KEY (ID), 
   CONSTRAINT FK_JOGADOR_POSICAO_JOGADOR FOREIGN KEY (JOGADOR_ID) REFERENCES JOGADOR(ID), 
   CONSTRAINT FK_JOGADOR_POSICAO_POSICAO FOREIGN KEY (POSICAO_ID) REFERENCES POSICAO(ID)   
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS PAIS (
   ID  BIGINT AUTO_INCREMENT NOT NULL,
   NOME  VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ESTADO (
   ID BIGINT AUTO_INCREMENT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   PAIS_ID BIGINT NOT NULL,
   PRIMARY KEY (ID), 
   CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MUNICIPIO (
   ID BIGINT AUTO_INCREMENT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   ESTADO_ID BIGINT NOT NULL,
   PRIMARY KEY (ID), 
   CONSTRAINT FK_MUNICIPIO_ESTADO FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BAIRRO (
   ID BIGINT AUTO_INCREMENT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   MUNICIPIO_ID BIGINT NOT NULL,
   PRIMARY KEY (ID), 
   CONSTRAINT FK_BAIRRO_MUNICIPIO FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIO(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ENDERECO (
   ID BIGINT AUTO_INCREMENT NOT NULL,
   CEP VARCHAR(8) NULL,
   BAIRRO_ID BIGINT NULL,
   LOGRADOURO VARCHAR(100) NULL,
   NUMERO VARCHAR(5) NULL,
   COMPLEMENTO VARCHAR(100) NULL,   
   PRIMARY KEY (ID), 
   CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (BAIRRO_ID) REFERENCES BAIRRO(ID)
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS CAMPEONATO (
   ID  BIGINT AUTO_INCREMENT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   DT_INICIO DATE NOT NULL,
   DT_FIM DATE NULL,
   QTD_JOGOS INTEGER NULL,
   DIAS_SEMANA VARCHAR(100) NULL,
   RESULTADO VARCHAR(10) NULL, /*eNUM = cAMPEÃO, 2 LUGAR, 3 LUGAR, 4,5,6,7,8,9,10, OUTRO....*/   
   LOCAL VARCHAR(50) NOT NULL,

   PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DESPESA(
   ID BIGINT AUTO_INCREMENT NOT NULL,
   DESCRICAO VARCHAR(100) NOT NULL
   PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RECEITA(
   ID BIGINT AUTO_INCREMENT NOT NULL,
   DESCRICAO VARCHAR(100) NOT NULL
   PRIMARY KEY (ID)
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS CAMPEONATO_JOGADOR (
   CAMPEONATO_ID BIGINT NULL,
   JOGADOR_ID BIGINT NULL,
   VALOR DECIMAL NOT NULL,
   PRIMARY KEY (CAMPEONATO_ID, JOGADOR_ID), 
   CONSTRAINT FK_CAMPEONATO_JOGADOR_CAMPEONATO FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO(ID), 
   CONSTRAINT FK_CAMPEONATO_JOGADOR_JOGADOR FOREIGN KEY (JOGADOR_ID) REFERENCES JOGADOR(ID) 
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS CAMPEONATO_DESPESA (
   CAMPEONATO_ID BIGINT NULL,
   DESPESA_ID BIGINT NULL,
   VALOR DECIMAL NOT NULL,
   PRIMARY KEY (CAMPEONATO_ID, DESPESA_ID), 
   CONSTRAINT FK_CAMPEONATO_JOGADOR_CAMPEONATO FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO(ID), 
   CONSTRAINT FK_CAMPEONATO_DESPESA_DESPESA FOREIGN KEY (DESPESA_ID) REFERENCES DESPESA(ID) 
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS CAMPEONATO_RECEITA (
   CAMPEONATO_ID BIGINT NULL,
   RECEITA_ID BIGINT NULL,
   VALOR DECIMAL NOT NULL,
   PRIMARY KEY (CAMPEONATO_ID, RECEITA_ID), 
   CONSTRAINT FK_CAMPEONATO_JOGADOR_CAMPEONATO FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO(ID), 
   CONSTRAINT FK_CAMPEONATO_RECEITA_RECEITA FOREIGN KEY (RECEITA_ID) REFERENCES RECEITA(ID) 
)ENGINE=InnoDB;


