INSERT INTO POSICAO (NOME, MODALIDADE) VALUES('GOLEIRO', 'CAMPO');
INSERT INTO POSICAO (NOME, MODALIDADE) VALUES('ZAGUEIRO ESQUERDO', 'CAMPO');
INSERT INTO POSICAO (NOME, MODALIDADE) VALUES('ZAGUEIRO DIREITO', 'CAMPO');
INSERT INTO POSICAO (NOME, MODALIDADE) VALUES('LATERAL DIREITO', 'CAMPO');
INSERT INTO POSICAO (NOME, MODALIDADE) VALUES('LATERAL ESQUERDO', 'CAMPO');
INSERT INTO POSICAO (NOME, MODALIDADE) VALUES('ZAGUEIRO', 'CAMPO');




	AREIA, CAMPO, SUIÇO
    POSICAO (GOLEIRO, ZAGUEIRO ESQUERDO, ZAGUEIRO DIREITO, LATERAL DIREITO, LATERAL ESQUERDO, CABEÇA AREA, MEIA DIREITA, MEIA ESQUERDA, ATACANTE ESQUERDO, ATACANTE DIREITO, CENTRO-AVANTE)
	FUTSAL (GOLEIRO, FIXO, ALA ESQUERDA, ALA DIREIRO, PIVÔ)
	ID
	