INSERT INTO MODALIDADES (DESCRICAO) VALUES('FUTSAL');/*1*/
INSERT INTO MODALIDADES (DESCRICAO) VALUES('CAMPO');/*2*/
INSERT INTO MODALIDADES (DESCRICAO) VALUES('SUICO');/*3*/
INSERT INTO MODALIDADES (DESCRICAO) VALUES('AREIA');/*4*/
INSERT INTO MODALIDADES (DESCRICAO) VALUES('OUTROS');/*5*/

INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('GOLEIRO', 1);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('FIXO', 1);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('ALA ESQUERDA', 1);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('ALA DIREIRO', 1);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('PIVÔ', 1);
	
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('GOLEIRO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('ZAGUEIRO ESQUERDO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('ZAGUEIRO DIREITO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('LATERAL DIREITO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('LATERAL ESQUERDO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('CABEÇA AREA', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('MEIA DIREITA', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('MEIA ESQUERDA', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('ATACANTE DIREITO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('ATACANTE ESQUERDO', 2);
INSERT INTO POSICOES (DESCRICAO, MODALIDADES_ID) VALUES('CENTRO-AVANTE', 2);


